/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 63
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 37
#define ALIAS_COUNT 0
#define TOKEN_COUNT 15
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_commit = 1,
  aux_sym_commit_line_token1 = 2,
  anon_sym_LF = 3,
  aux_sym_sha_token1 = 4,
  aux_sym_sha_token2 = 5,
  sym_comment = 6,
  sym_info_key = 7,
  sym_info_value = 8,
  aux_sym_blank_line_token1 = 9,
  sym_subject_text = 10,
  aux_sym_overflow_token1 = 11,
  sym_trailer_key = 12,
  sym__indent = 13,
  sym_invalid_line = 14,
  sym_document = 15,
  sym_commit = 16,
  sym_commit_line = 17,
  sym_sha = 18,
  sym_info_line = 19,
  sym_blank_line = 20,
  sym_message = 21,
  sym__noise = 22,
  sym_paragraph = 23,
  sym_trailers = 24,
  sym_subject = 25,
  sym_overflow = 26,
  sym_message_line = 27,
  sym_trailer_line = 28,
  sym_text = 29,
  aux_sym_document_repeat1 = 30,
  aux_sym_document_repeat2 = 31,
  aux_sym_commit_repeat1 = 32,
  aux_sym_message_repeat1 = 33,
  aux_sym_message_repeat2 = 34,
  aux_sym_paragraph_repeat1 = 35,
  aux_sym_trailers_repeat1 = 36,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_commit] = "commit",
  [aux_sym_commit_line_token1] = "commit_line_token1",
  [anon_sym_LF] = "\n",
  [aux_sym_sha_token1] = "short_sha",
  [aux_sym_sha_token2] = "sha_token2",
  [sym_comment] = "comment",
  [sym_info_key] = "info_key",
  [sym_info_value] = "info_value",
  [aux_sym_blank_line_token1] = "blank_line_token1",
  [sym_subject_text] = "subject_text",
  [aux_sym_overflow_token1] = "overflow_token1",
  [sym_trailer_key] = "trailer_key",
  [sym__indent] = "_indent",
  [sym_invalid_line] = "invalid_line",
  [sym_document] = "document",
  [sym_commit] = "commit",
  [sym_commit_line] = "commit_line",
  [sym_sha] = "sha",
  [sym_info_line] = "info_line",
  [sym_blank_line] = "blank_line",
  [sym_message] = "message",
  [sym__noise] = "_noise",
  [sym_paragraph] = "paragraph",
  [sym_trailers] = "trailers",
  [sym_subject] = "subject",
  [sym_overflow] = "overflow",
  [sym_message_line] = "message_line",
  [sym_trailer_line] = "trailer_line",
  [sym_text] = "text",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_document_repeat2] = "document_repeat2",
  [aux_sym_commit_repeat1] = "commit_repeat1",
  [aux_sym_message_repeat1] = "message_repeat1",
  [aux_sym_message_repeat2] = "message_repeat2",
  [aux_sym_paragraph_repeat1] = "paragraph_repeat1",
  [aux_sym_trailers_repeat1] = "trailers_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_commit] = anon_sym_commit,
  [aux_sym_commit_line_token1] = aux_sym_commit_line_token1,
  [anon_sym_LF] = anon_sym_LF,
  [aux_sym_sha_token1] = aux_sym_sha_token1,
  [aux_sym_sha_token2] = aux_sym_sha_token2,
  [sym_comment] = sym_comment,
  [sym_info_key] = sym_info_key,
  [sym_info_value] = sym_info_value,
  [aux_sym_blank_line_token1] = aux_sym_blank_line_token1,
  [sym_subject_text] = sym_subject_text,
  [aux_sym_overflow_token1] = aux_sym_overflow_token1,
  [sym_trailer_key] = sym_trailer_key,
  [sym__indent] = sym__indent,
  [sym_invalid_line] = sym_invalid_line,
  [sym_document] = sym_document,
  [sym_commit] = sym_commit,
  [sym_commit_line] = sym_commit_line,
  [sym_sha] = sym_sha,
  [sym_info_line] = sym_info_line,
  [sym_blank_line] = sym_blank_line,
  [sym_message] = sym_message,
  [sym__noise] = sym__noise,
  [sym_paragraph] = sym_paragraph,
  [sym_trailers] = sym_trailers,
  [sym_subject] = sym_subject,
  [sym_overflow] = sym_overflow,
  [sym_message_line] = sym_message_line,
  [sym_trailer_line] = sym_trailer_line,
  [sym_text] = sym_text,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_document_repeat2] = aux_sym_document_repeat2,
  [aux_sym_commit_repeat1] = aux_sym_commit_repeat1,
  [aux_sym_message_repeat1] = aux_sym_message_repeat1,
  [aux_sym_message_repeat2] = aux_sym_message_repeat2,
  [aux_sym_paragraph_repeat1] = aux_sym_paragraph_repeat1,
  [aux_sym_trailers_repeat1] = aux_sym_trailers_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_commit] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_commit_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_sha_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_sha_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_info_key] = {
    .visible = true,
    .named = true,
  },
  [sym_info_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_blank_line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_subject_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_overflow_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_trailer_key] = {
    .visible = true,
    .named = true,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym_invalid_line] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_commit] = {
    .visible = true,
    .named = true,
  },
  [sym_commit_line] = {
    .visible = true,
    .named = true,
  },
  [sym_sha] = {
    .visible = true,
    .named = true,
  },
  [sym_info_line] = {
    .visible = true,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_message] = {
    .visible = true,
    .named = true,
  },
  [sym__noise] = {
    .visible = false,
    .named = true,
  },
  [sym_paragraph] = {
    .visible = true,
    .named = true,
  },
  [sym_trailers] = {
    .visible = true,
    .named = true,
  },
  [sym_subject] = {
    .visible = true,
    .named = true,
  },
  [sym_overflow] = {
    .visible = true,
    .named = true,
  },
  [sym_message_line] = {
    .visible = true,
    .named = true,
  },
  [sym_trailer_line] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_document_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_commit_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_message_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_message_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_paragraph_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_trailers_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_overflow = 2,
  field_sha = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_overflow] = "overflow",
  [field_sha] = "sha",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
  [4] = {.index = 4, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_sha, 2},
  [1] =
    {field_key, 0},
    {field_value, 1},
  [3] =
    {field_overflow, 2},
  [4] =
    {field_key, 1},
    {field_value, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(34);
      if (lookahead == '\t') ADVANCE(201);
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == ' ') ADVANCE(39);
      if (lookahead == '#') ADVANCE(6);
      if (lookahead == 'c') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(23);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == ' ') ADVANCE(201);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(22);
      END_STATE();
    case 2:
      if (lookahead == '\t') ADVANCE(23);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == ' ') ADVANCE(1);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(22);
      END_STATE();
    case 3:
      if (lookahead == '\t') ADVANCE(23);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == ' ') ADVANCE(2);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(22);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(40);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(47);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(199);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(48);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(202);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead == 'i') ADVANCE(11);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(22);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(202);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead == 'm') ADVANCE(7);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(22);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(202);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead == 'm') ADVANCE(8);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(22);
      END_STATE();
    case 10:
      if (lookahead == '\n') ADVANCE(202);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead == 'o') ADVANCE(9);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(22);
      END_STATE();
    case 11:
      if (lookahead == '\n') ADVANCE(202);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead == 't') ADVANCE(36);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(22);
      END_STATE();
    case 12:
      if (lookahead == '\n') ADVANCE(202);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(22);
      END_STATE();
    case 13:
      if (lookahead == '\n') ADVANCE(202);
      if (lookahead == 'i') ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(22);
      END_STATE();
    case 14:
      if (lookahead == '\n') ADVANCE(202);
      if (lookahead == 'm') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(22);
      END_STATE();
    case 15:
      if (lookahead == '\n') ADVANCE(202);
      if (lookahead == 'm') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(22);
      END_STATE();
    case 16:
      if (lookahead == '\n') ADVANCE(202);
      if (lookahead == 'o') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(22);
      END_STATE();
    case 17:
      if (lookahead == '\n') ADVANCE(202);
      if (lookahead == 'o') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(22);
      END_STATE();
    case 18:
      if (lookahead == '\n') ADVANCE(202);
      if (lookahead == 't') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(22);
      END_STATE();
    case 19:
      if (lookahead == '\n') ADVANCE(202);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(46);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(22);
      END_STATE();
    case 20:
      if (lookahead == '\n') ADVANCE(202);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(22);
      END_STATE();
    case 21:
      if (lookahead == '\n') ADVANCE(202);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(22);
      END_STATE();
    case 22:
      if (lookahead == '\n') ADVANCE(202);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(22);
      END_STATE();
    case 23:
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(22);
      END_STATE();
    case 24:
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(196);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(199);
      END_STATE();
    case 25:
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(124);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(195);
      END_STATE();
    case 26:
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(26);
      END_STATE();
    case 27:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(46);
      END_STATE();
    case 28:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(27);
      END_STATE();
    case 29:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(28);
      END_STATE();
    case 30:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(29);
      END_STATE();
    case 31:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(199);
      END_STATE();
    case 32:
      if (eof) ADVANCE(34);
      if (lookahead == '\t') ADVANCE(201);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == ' ') ADVANCE(3);
      if (lookahead == '#') ADVANCE(6);
      if (lookahead == 'c') ADVANCE(17);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(22);
      END_STATE();
    case 33:
      if (eof) ADVANCE(34);
      if (lookahead == '\t') ADVANCE(201);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == ' ') ADVANCE(3);
      if (lookahead == '#') ADVANCE(6);
      if (lookahead == 'c') ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(22);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_commit);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_commit);
      if (lookahead == ':') ADVANCE(49);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym_commit_line_token1);
      if (lookahead == '\t') ADVANCE(40);
      if (lookahead == ' ') ADVANCE(201);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym_commit_line_token1);
      if (lookahead == '\t') ADVANCE(40);
      if (lookahead == ' ') ADVANCE(37);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym_commit_line_token1);
      if (lookahead == '\t') ADVANCE(40);
      if (lookahead == ' ') ADVANCE(38);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym_commit_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(aux_sym_sha_token1);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_sha_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(42);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_sha_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(43);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(aux_sym_sha_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(44);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(aux_sym_sha_token1);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(45);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_sha_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(47);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_info_key);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_info_value);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(aux_sym_blank_line_token1);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_subject_text);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(54);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(52);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(26);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(125);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(55);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(126);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(127);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(57);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(128);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(58);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(59);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(130);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(60);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(131);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(61);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(132);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(62);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(133);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(63);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(134);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(64);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(135);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(65);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(66);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(137);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(67);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(138);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(68);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(139);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(69);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(140);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(70);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(141);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(71);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(142);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(72);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(143);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(73);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(144);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(74);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(145);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(75);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(146);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(76);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(147);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(77);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(148);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(78);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(149);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(79);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(150);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(80);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(151);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(81);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(152);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(82);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(83);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(154);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(84);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(155);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(85);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(156);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(86);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(157);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(87);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(158);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(88);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(159);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(89);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(160);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(90);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(161);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(91);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(162);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(93);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(164);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(94);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(165);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(166);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(96);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(167);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(97);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(168);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(98);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(169);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(99);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(170);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(100);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(171);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(101);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(172);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(102);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(173);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(103);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(174);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(104);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(175);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(105);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(176);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(106);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(177);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(107);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(178);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(108);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(179);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(109);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(180);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(110);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(181);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(111);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(182);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(112);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(183);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(113);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(184);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(114);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(185);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(115);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(186);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(116);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(187);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(117);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(188);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(118);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(189);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(119);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(190);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(120);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(191);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(121);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(192);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(122);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(193);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(123);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(194);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(52);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(125);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(126);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(127);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(128);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(129);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(130);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(131);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(132);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(133);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(134);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(135);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(136);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(137);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(138);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(139);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(140);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(141);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(142);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(143);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(144);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(145);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(146);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(147);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(148);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(149);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(150);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(151);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(152);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(153);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(154);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(155);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(156);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(157);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(158);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(159);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(160);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(161);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(162);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(163);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(164);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(165);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(166);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(167);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(168);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(169);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(170);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(171);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(172);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(173);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(174);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(175);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(176);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(177);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(178);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(179);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(180);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(181);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(182);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(183);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(184);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(185);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(186);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(187);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(188);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(189);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(190);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(191);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(192);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(193);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(194);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(aux_sym_overflow_token1);
      if (lookahead == '\n') ADVANCE(51);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(196);
      if (lookahead != 0 &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(199);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(aux_sym_overflow_token1);
      if (lookahead == ':') ADVANCE(198);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(197);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(199);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(aux_sym_overflow_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(200);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(199);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(aux_sym_overflow_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x17f &&
          lookahead != 0x212a) ADVANCE(199);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(sym_trailer_key);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(sym__indent);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(sym_invalid_line);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 32},
  [2] = {.lex_state = 32},
  [3] = {.lex_state = 32},
  [4] = {.lex_state = 33},
  [5] = {.lex_state = 33},
  [6] = {.lex_state = 32},
  [7] = {.lex_state = 32},
  [8] = {.lex_state = 33},
  [9] = {.lex_state = 32},
  [10] = {.lex_state = 32},
  [11] = {.lex_state = 32},
  [12] = {.lex_state = 32},
  [13] = {.lex_state = 32},
  [14] = {.lex_state = 32},
  [15] = {.lex_state = 32},
  [16] = {.lex_state = 32},
  [17] = {.lex_state = 32},
  [18] = {.lex_state = 32},
  [19] = {.lex_state = 32},
  [20] = {.lex_state = 32},
  [21] = {.lex_state = 33},
  [22] = {.lex_state = 33},
  [23] = {.lex_state = 33},
  [24] = {.lex_state = 33},
  [25] = {.lex_state = 33},
  [26] = {.lex_state = 32},
  [27] = {.lex_state = 32},
  [28] = {.lex_state = 32},
  [29] = {.lex_state = 32},
  [30] = {.lex_state = 32},
  [31] = {.lex_state = 32},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 24},
  [36] = {.lex_state = 24},
  [37] = {.lex_state = 5},
  [38] = {.lex_state = 4},
  [39] = {.lex_state = 31},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 30},
  [42] = {.lex_state = 25},
  [43] = {.lex_state = 4},
  [44] = {.lex_state = 4},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 5},
  [47] = {.lex_state = 5},
  [48] = {.lex_state = 5},
  [49] = {.lex_state = 4},
  [50] = {.lex_state = 50},
  [51] = {.lex_state = 24},
  [52] = {.lex_state = 0},
  [53] = {.lex_state = 0},
  [54] = {.lex_state = 0},
  [55] = {.lex_state = 0},
  [56] = {.lex_state = 24},
  [57] = {.lex_state = 0},
  [58] = {.lex_state = 0},
  [59] = {.lex_state = 0},
  [60] = {.lex_state = 0},
  [61] = {.lex_state = 0},
  [62] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_commit] = ACTIONS(1),
    [aux_sym_commit_line_token1] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [aux_sym_sha_token1] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym_invalid_line] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(62),
    [sym_commit] = STATE(32),
    [sym_commit_line] = STATE(4),
    [sym_blank_line] = STATE(6),
    [aux_sym_document_repeat1] = STATE(6),
    [aux_sym_document_repeat2] = STATE(32),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_commit] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [aux_sym_blank_line_token1] = ACTIONS(9),
    [sym__indent] = ACTIONS(11),
    [sym_invalid_line] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 9,
    ACTIONS(9), 1,
      aux_sym_blank_line_token1,
    ACTIONS(17), 1,
      sym_comment,
    ACTIONS(19), 1,
      sym__indent,
    ACTIONS(21), 1,
      sym_invalid_line,
    STATE(12), 1,
      sym_trailers,
    STATE(14), 1,
      sym_trailer_line,
    STATE(16), 1,
      sym_message_line,
    ACTIONS(15), 2,
      ts_builtin_sym_end,
      anon_sym_commit,
    STATE(7), 4,
      sym_blank_line,
      sym__noise,
      sym_paragraph,
      aux_sym_message_repeat1,
  [32] = 9,
    ACTIONS(9), 1,
      aux_sym_blank_line_token1,
    ACTIONS(19), 1,
      sym__indent,
    ACTIONS(25), 1,
      sym_comment,
    ACTIONS(27), 1,
      sym_invalid_line,
    STATE(10), 1,
      sym_trailers,
    STATE(14), 1,
      sym_trailer_line,
    STATE(16), 1,
      sym_message_line,
    ACTIONS(23), 2,
      ts_builtin_sym_end,
      anon_sym_commit,
    STATE(2), 4,
      sym_blank_line,
      sym__noise,
      sym_paragraph,
      aux_sym_message_repeat1,
  [64] = 10,
    ACTIONS(9), 1,
      aux_sym_blank_line_token1,
    ACTIONS(29), 1,
      ts_builtin_sym_end,
    ACTIONS(31), 1,
      anon_sym_commit,
    ACTIONS(33), 1,
      sym_comment,
    ACTIONS(35), 1,
      sym_info_key,
    ACTIONS(37), 1,
      sym__indent,
    ACTIONS(39), 1,
      sym_invalid_line,
    STATE(3), 1,
      sym_subject,
    STATE(45), 1,
      sym_message,
    STATE(5), 3,
      sym_info_line,
      sym_blank_line,
      aux_sym_commit_repeat1,
  [97] = 10,
    ACTIONS(9), 1,
      aux_sym_blank_line_token1,
    ACTIONS(35), 1,
      sym_info_key,
    ACTIONS(37), 1,
      sym__indent,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      anon_sym_commit,
    ACTIONS(45), 1,
      sym_comment,
    ACTIONS(47), 1,
      sym_invalid_line,
    STATE(3), 1,
      sym_subject,
    STATE(40), 1,
      sym_message,
    STATE(8), 3,
      sym_info_line,
      sym_blank_line,
      aux_sym_commit_repeat1,
  [130] = 9,
    ACTIONS(5), 1,
      anon_sym_commit,
    ACTIONS(9), 1,
      aux_sym_blank_line_token1,
    ACTIONS(11), 1,
      sym__indent,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    ACTIONS(51), 1,
      sym_comment,
    ACTIONS(53), 1,
      sym_invalid_line,
    STATE(4), 1,
      sym_commit_line,
    STATE(15), 2,
      sym_blank_line,
      aux_sym_document_repeat1,
    STATE(33), 2,
      sym_commit,
      aux_sym_document_repeat2,
  [160] = 7,
    ACTIONS(57), 1,
      sym_comment,
    ACTIONS(60), 1,
      aux_sym_blank_line_token1,
    ACTIONS(63), 1,
      sym__indent,
    ACTIONS(66), 1,
      sym_invalid_line,
    STATE(16), 1,
      sym_message_line,
    ACTIONS(55), 2,
      ts_builtin_sym_end,
      anon_sym_commit,
    STATE(7), 4,
      sym_blank_line,
      sym__noise,
      sym_paragraph,
      aux_sym_message_repeat1,
  [186] = 8,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    ACTIONS(71), 1,
      anon_sym_commit,
    ACTIONS(73), 1,
      sym_comment,
    ACTIONS(76), 1,
      sym_info_key,
    ACTIONS(79), 1,
      aux_sym_blank_line_token1,
    ACTIONS(82), 1,
      sym__indent,
    ACTIONS(85), 1,
      sym_invalid_line,
    STATE(8), 3,
      sym_info_line,
      sym_blank_line,
      aux_sym_commit_repeat1,
  [213] = 6,
    ACTIONS(9), 1,
      aux_sym_blank_line_token1,
    ACTIONS(11), 1,
      sym__indent,
    ACTIONS(90), 1,
      sym_comment,
    ACTIONS(92), 1,
      sym_invalid_line,
    ACTIONS(88), 2,
      ts_builtin_sym_end,
      anon_sym_commit,
    STATE(13), 3,
      sym_blank_line,
      sym__noise,
      aux_sym_message_repeat2,
  [235] = 6,
    ACTIONS(9), 1,
      aux_sym_blank_line_token1,
    ACTIONS(11), 1,
      sym__indent,
    ACTIONS(94), 1,
      sym_comment,
    ACTIONS(96), 1,
      sym_invalid_line,
    ACTIONS(15), 2,
      ts_builtin_sym_end,
      anon_sym_commit,
    STATE(11), 3,
      sym_blank_line,
      sym__noise,
      aux_sym_message_repeat2,
  [257] = 6,
    ACTIONS(9), 1,
      aux_sym_blank_line_token1,
    ACTIONS(11), 1,
      sym__indent,
    ACTIONS(90), 1,
      sym_comment,
    ACTIONS(92), 1,
      sym_invalid_line,
    ACTIONS(98), 2,
      ts_builtin_sym_end,
      anon_sym_commit,
    STATE(13), 3,
      sym_blank_line,
      sym__noise,
      aux_sym_message_repeat2,
  [279] = 6,
    ACTIONS(9), 1,
      aux_sym_blank_line_token1,
    ACTIONS(11), 1,
      sym__indent,
    ACTIONS(100), 1,
      sym_comment,
    ACTIONS(102), 1,
      sym_invalid_line,
    ACTIONS(98), 2,
      ts_builtin_sym_end,
      anon_sym_commit,
    STATE(9), 3,
      sym_blank_line,
      sym__noise,
      aux_sym_message_repeat2,
  [301] = 6,
    ACTIONS(106), 1,
      sym_comment,
    ACTIONS(109), 1,
      aux_sym_blank_line_token1,
    ACTIONS(112), 1,
      sym__indent,
    ACTIONS(115), 1,
      sym_invalid_line,
    ACTIONS(104), 2,
      ts_builtin_sym_end,
      anon_sym_commit,
    STATE(13), 3,
      sym_blank_line,
      sym__noise,
      aux_sym_message_repeat2,
  [323] = 6,
    ACTIONS(120), 1,
      sym_comment,
    ACTIONS(122), 1,
      aux_sym_blank_line_token1,
    ACTIONS(124), 1,
      sym__indent,
    ACTIONS(126), 1,
      sym_invalid_line,
    ACTIONS(118), 2,
      ts_builtin_sym_end,
      anon_sym_commit,
    STATE(17), 2,
      sym_trailer_line,
      aux_sym_trailers_repeat1,
  [344] = 6,
    ACTIONS(130), 1,
      sym_comment,
    ACTIONS(133), 1,
      aux_sym_blank_line_token1,
    ACTIONS(136), 1,
      sym__indent,
    ACTIONS(139), 1,
      sym_invalid_line,
    ACTIONS(128), 2,
      ts_builtin_sym_end,
      anon_sym_commit,
    STATE(15), 2,
      sym_blank_line,
      aux_sym_document_repeat1,
  [365] = 6,
    ACTIONS(144), 1,
      sym_comment,
    ACTIONS(146), 1,
      aux_sym_blank_line_token1,
    ACTIONS(148), 1,
      sym__indent,
    ACTIONS(150), 1,
      sym_invalid_line,
    ACTIONS(142), 2,
      ts_builtin_sym_end,
      anon_sym_commit,
    STATE(18), 2,
      sym_message_line,
      aux_sym_paragraph_repeat1,
  [386] = 6,
    ACTIONS(124), 1,
      sym__indent,
    ACTIONS(154), 1,
      sym_comment,
    ACTIONS(156), 1,
      aux_sym_blank_line_token1,
    ACTIONS(158), 1,
      sym_invalid_line,
    ACTIONS(152), 2,
      ts_builtin_sym_end,
      anon_sym_commit,
    STATE(20), 2,
      sym_trailer_line,
      aux_sym_trailers_repeat1,
  [407] = 6,
    ACTIONS(148), 1,
      sym__indent,
    ACTIONS(162), 1,
      sym_comment,
    ACTIONS(164), 1,
      aux_sym_blank_line_token1,
    ACTIONS(166), 1,
      sym_invalid_line,
    ACTIONS(160), 2,
      ts_builtin_sym_end,
      anon_sym_commit,
    STATE(19), 2,
      sym_message_line,
      aux_sym_paragraph_repeat1,
  [428] = 6,
    ACTIONS(170), 1,
      sym_comment,
    ACTIONS(173), 1,
      aux_sym_blank_line_token1,
    ACTIONS(175), 1,
      sym__indent,
    ACTIONS(178), 1,
      sym_invalid_line,
    ACTIONS(168), 2,
      ts_builtin_sym_end,
      anon_sym_commit,
    STATE(19), 2,
      sym_message_line,
      aux_sym_paragraph_repeat1,
  [449] = 6,
    ACTIONS(183), 1,
      sym_comment,
    ACTIONS(186), 1,
      aux_sym_blank_line_token1,
    ACTIONS(188), 1,
      sym__indent,
    ACTIONS(191), 1,
      sym_invalid_line,
    ACTIONS(181), 2,
      ts_builtin_sym_end,
      anon_sym_commit,
    STATE(20), 2,
      sym_trailer_line,
      aux_sym_trailers_repeat1,
  [470] = 2,
    ACTIONS(196), 3,
      anon_sym_commit,
      aux_sym_blank_line_token1,
      sym_invalid_line,
    ACTIONS(194), 4,
      ts_builtin_sym_end,
      sym_comment,
      sym_info_key,
      sym__indent,
  [482] = 2,
    ACTIONS(200), 3,
      anon_sym_commit,
      aux_sym_blank_line_token1,
      sym_invalid_line,
    ACTIONS(198), 4,
      ts_builtin_sym_end,
      sym_comment,
      sym_info_key,
      sym__indent,
  [494] = 2,
    ACTIONS(204), 3,
      anon_sym_commit,
      aux_sym_blank_line_token1,
      sym_invalid_line,
    ACTIONS(202), 4,
      ts_builtin_sym_end,
      sym_comment,
      sym_info_key,
      sym__indent,
  [506] = 2,
    ACTIONS(208), 3,
      anon_sym_commit,
      aux_sym_blank_line_token1,
      sym_invalid_line,
    ACTIONS(206), 4,
      ts_builtin_sym_end,
      sym_comment,
      sym_info_key,
      sym__indent,
  [518] = 2,
    ACTIONS(212), 3,
      anon_sym_commit,
      aux_sym_blank_line_token1,
      sym_invalid_line,
    ACTIONS(210), 4,
      ts_builtin_sym_end,
      sym_comment,
      sym_info_key,
      sym__indent,
  [530] = 2,
    ACTIONS(216), 2,
      aux_sym_blank_line_token1,
      sym_invalid_line,
    ACTIONS(214), 4,
      ts_builtin_sym_end,
      anon_sym_commit,
      sym_comment,
      sym__indent,
  [541] = 2,
    ACTIONS(220), 2,
      aux_sym_blank_line_token1,
      sym_invalid_line,
    ACTIONS(218), 4,
      ts_builtin_sym_end,
      anon_sym_commit,
      sym_comment,
      sym__indent,
  [552] = 2,
    ACTIONS(224), 2,
      aux_sym_blank_line_token1,
      sym_invalid_line,
    ACTIONS(222), 4,
      ts_builtin_sym_end,
      anon_sym_commit,
      sym_comment,
      sym__indent,
  [563] = 2,
    ACTIONS(229), 2,
      aux_sym_blank_line_token1,
      sym_invalid_line,
    ACTIONS(226), 4,
      ts_builtin_sym_end,
      anon_sym_commit,
      sym_comment,
      sym__indent,
  [574] = 2,
    ACTIONS(234), 2,
      aux_sym_blank_line_token1,
      sym_invalid_line,
    ACTIONS(232), 4,
      ts_builtin_sym_end,
      anon_sym_commit,
      sym_comment,
      sym__indent,
  [585] = 2,
    ACTIONS(238), 2,
      aux_sym_blank_line_token1,
      sym_invalid_line,
    ACTIONS(236), 4,
      ts_builtin_sym_end,
      anon_sym_commit,
      sym_comment,
      sym__indent,
  [596] = 4,
    ACTIONS(5), 1,
      anon_sym_commit,
    ACTIONS(49), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_commit_line,
    STATE(34), 2,
      sym_commit,
      aux_sym_document_repeat2,
  [610] = 4,
    ACTIONS(5), 1,
      anon_sym_commit,
    ACTIONS(240), 1,
      ts_builtin_sym_end,
    STATE(4), 1,
      sym_commit_line,
    STATE(34), 2,
      sym_commit,
      aux_sym_document_repeat2,
  [624] = 4,
    ACTIONS(242), 1,
      ts_builtin_sym_end,
    ACTIONS(244), 1,
      anon_sym_commit,
    STATE(4), 1,
      sym_commit_line,
    STATE(34), 2,
      sym_commit,
      aux_sym_document_repeat2,
  [638] = 4,
    ACTIONS(247), 1,
      aux_sym_blank_line_token1,
    ACTIONS(249), 1,
      aux_sym_overflow_token1,
    ACTIONS(251), 1,
      sym_trailer_key,
    STATE(61), 1,
      sym_text,
  [651] = 4,
    ACTIONS(247), 1,
      aux_sym_blank_line_token1,
    ACTIONS(249), 1,
      aux_sym_overflow_token1,
    ACTIONS(253), 1,
      sym_trailer_key,
    STATE(61), 1,
      sym_text,
  [664] = 3,
    ACTIONS(255), 1,
      anon_sym_LF,
    ACTIONS(257), 1,
      aux_sym_overflow_token1,
    STATE(57), 1,
      sym_overflow,
  [674] = 2,
    ACTIONS(261), 1,
      aux_sym_sha_token2,
    ACTIONS(259), 2,
      aux_sym_commit_line_token1,
      anon_sym_LF,
  [682] = 3,
    ACTIONS(249), 1,
      aux_sym_overflow_token1,
    ACTIONS(253), 1,
      sym_trailer_key,
    STATE(61), 1,
      sym_text,
  [692] = 1,
    ACTIONS(263), 2,
      ts_builtin_sym_end,
      anon_sym_commit,
  [697] = 2,
    ACTIONS(265), 1,
      aux_sym_sha_token1,
    STATE(43), 1,
      sym_sha,
  [704] = 2,
    ACTIONS(247), 1,
      aux_sym_blank_line_token1,
    ACTIONS(267), 1,
      sym_subject_text,
  [711] = 2,
    ACTIONS(269), 1,
      aux_sym_commit_line_token1,
    ACTIONS(271), 1,
      anon_sym_LF,
  [718] = 1,
    ACTIONS(273), 2,
      aux_sym_commit_line_token1,
      anon_sym_LF,
  [723] = 1,
    ACTIONS(41), 2,
      ts_builtin_sym_end,
      anon_sym_commit,
  [728] = 2,
    ACTIONS(275), 1,
      aux_sym_overflow_token1,
    STATE(59), 1,
      sym_text,
  [735] = 2,
    ACTIONS(275), 1,
      aux_sym_overflow_token1,
    STATE(53), 1,
      sym_text,
  [742] = 2,
    ACTIONS(275), 1,
      aux_sym_overflow_token1,
    STATE(60), 1,
      sym_text,
  [749] = 1,
    ACTIONS(277), 1,
      aux_sym_commit_line_token1,
  [753] = 1,
    ACTIONS(279), 1,
      sym_info_value,
  [757] = 1,
    ACTIONS(281), 1,
      sym_trailer_key,
  [761] = 1,
    ACTIONS(283), 1,
      anon_sym_LF,
  [765] = 1,
    ACTIONS(285), 1,
      anon_sym_LF,
  [769] = 1,
    ACTIONS(287), 1,
      anon_sym_LF,
  [773] = 1,
    ACTIONS(289), 1,
      anon_sym_LF,
  [777] = 1,
    ACTIONS(247), 1,
      aux_sym_blank_line_token1,
  [781] = 1,
    ACTIONS(291), 1,
      anon_sym_LF,
  [785] = 1,
    ACTIONS(293), 1,
      anon_sym_LF,
  [789] = 1,
    ACTIONS(295), 1,
      anon_sym_LF,
  [793] = 1,
    ACTIONS(297), 1,
      anon_sym_LF,
  [797] = 1,
    ACTIONS(299), 1,
      anon_sym_LF,
  [801] = 1,
    ACTIONS(301), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 32,
  [SMALL_STATE(4)] = 64,
  [SMALL_STATE(5)] = 97,
  [SMALL_STATE(6)] = 130,
  [SMALL_STATE(7)] = 160,
  [SMALL_STATE(8)] = 186,
  [SMALL_STATE(9)] = 213,
  [SMALL_STATE(10)] = 235,
  [SMALL_STATE(11)] = 257,
  [SMALL_STATE(12)] = 279,
  [SMALL_STATE(13)] = 301,
  [SMALL_STATE(14)] = 323,
  [SMALL_STATE(15)] = 344,
  [SMALL_STATE(16)] = 365,
  [SMALL_STATE(17)] = 386,
  [SMALL_STATE(18)] = 407,
  [SMALL_STATE(19)] = 428,
  [SMALL_STATE(20)] = 449,
  [SMALL_STATE(21)] = 470,
  [SMALL_STATE(22)] = 482,
  [SMALL_STATE(23)] = 494,
  [SMALL_STATE(24)] = 506,
  [SMALL_STATE(25)] = 518,
  [SMALL_STATE(26)] = 530,
  [SMALL_STATE(27)] = 541,
  [SMALL_STATE(28)] = 552,
  [SMALL_STATE(29)] = 563,
  [SMALL_STATE(30)] = 574,
  [SMALL_STATE(31)] = 585,
  [SMALL_STATE(32)] = 596,
  [SMALL_STATE(33)] = 610,
  [SMALL_STATE(34)] = 624,
  [SMALL_STATE(35)] = 638,
  [SMALL_STATE(36)] = 651,
  [SMALL_STATE(37)] = 664,
  [SMALL_STATE(38)] = 674,
  [SMALL_STATE(39)] = 682,
  [SMALL_STATE(40)] = 692,
  [SMALL_STATE(41)] = 697,
  [SMALL_STATE(42)] = 704,
  [SMALL_STATE(43)] = 711,
  [SMALL_STATE(44)] = 718,
  [SMALL_STATE(45)] = 723,
  [SMALL_STATE(46)] = 728,
  [SMALL_STATE(47)] = 735,
  [SMALL_STATE(48)] = 742,
  [SMALL_STATE(49)] = 749,
  [SMALL_STATE(50)] = 753,
  [SMALL_STATE(51)] = 757,
  [SMALL_STATE(52)] = 761,
  [SMALL_STATE(53)] = 765,
  [SMALL_STATE(54)] = 769,
  [SMALL_STATE(55)] = 773,
  [SMALL_STATE(56)] = 777,
  [SMALL_STATE(57)] = 781,
  [SMALL_STATE(58)] = 785,
  [SMALL_STATE(59)] = 789,
  [SMALL_STATE(60)] = 793,
  [SMALL_STATE(61)] = 797,
  [SMALL_STATE(62)] = 801,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(56),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 2, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 1, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_commit, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_commit, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_commit, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_commit, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_message_repeat1, 2, 0, 0),
  [57] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_message_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_message_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_message_repeat1, 2, 0, 0), SHIFT_REPEAT(36),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_message_repeat1, 2, 0, 0), SHIFT_REPEAT(7),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_commit_repeat1, 2, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_commit_repeat1, 2, 0, 0),
  [73] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_commit_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_commit_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_commit_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_commit_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_commit_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 4, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [92] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [96] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [98] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [102] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_message_repeat2, 2, 0, 0),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_message_repeat2, 2, 0, 0), SHIFT_REPEAT(13),
  [109] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_message_repeat2, 2, 0, 0), SHIFT_REPEAT(22),
  [112] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_message_repeat2, 2, 0, 0), SHIFT_REPEAT(56),
  [115] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_message_repeat2, 2, 0, 0), SHIFT_REPEAT(13),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trailers, 1, 1, 0),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_trailers, 1, 1, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(51),
  [126] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [130] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [133] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [136] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(56),
  [139] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [142] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 1, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 1, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [150] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trailers, 2, 1, 0),
  [154] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [156] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_trailers, 2, 1, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paragraph, 2, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [164] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paragraph, 2, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0),
  [170] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0),
  [175] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [178] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_paragraph_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [181] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_trailers_repeat1, 2, 0, 0),
  [183] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_trailers_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [186] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_trailers_repeat1, 2, 0, 0),
  [188] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_trailers_repeat1, 2, 0, 0), SHIFT_REPEAT(51),
  [191] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_trailers_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_commit_line, 4, 0, 1),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_commit_line, 4, 0, 1),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blank_line, 1, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_blank_line, 1, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_info_line, 3, 0, 2),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_info_line, 3, 0, 2),
  [206] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blank_line, 2, 0, 0),
  [208] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_blank_line, 2, 0, 0),
  [210] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_commit_line, 5, 0, 1),
  [212] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_commit_line, 5, 0, 1),
  [214] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 3, 0, 0),
  [216] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subject, 3, 0, 0),
  [218] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 4, 0, 3),
  [220] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subject, 4, 0, 3),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_line, 3, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_message_line, 3, 0, 0),
  [226] = {.entry = {.count = 2, .reusable = true}}, REDUCE(sym_message_line, 4, 0, 0), REDUCE(sym_trailer_line, 4, 0, 4),
  [229] = {.entry = {.count = 2, .reusable = false}}, REDUCE(sym_message_line, 4, 0, 0), REDUCE(sym_trailer_line, 4, 0, 4),
  [232] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_line, 4, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_message_line, 4, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_trailer_line, 4, 0, 4),
  [238] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_trailer_line, 4, 0, 4),
  [240] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0),
  [244] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(49),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [249] = {.entry = {.count = 1, .reusable = false}}, SHIFT(58),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(55),
  [259] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sha, 1, 0, 0),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [263] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_commit, 3, 0, 0),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [267] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [273] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sha, 2, 0, 0),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [281] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_overflow, 1, 0, 0),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 0),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [301] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_reword(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "reword",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
