/* Automatically @generated by tree-sitter v0.25.4 (726dcd1e872149d95de581589fc408fb8ea9cb0b) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 40
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 4
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 4
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_commit = 1,
  aux_sym_commit_line_token1 = 2,
  anon_sym_LF = 3,
  aux_sym_sha_token1 = 4,
  aux_sym_sha_token2 = 5,
  sym_comment = 6,
  sym_info_key = 7,
  sym_info_value = 8,
  aux_sym_blank_line_token1 = 9,
  sym_subject_text = 10,
  aux_sym_overflow_token1 = 11,
  sym__indent = 12,
  sym_invalid_line = 13,
  sym_document = 14,
  sym_commit = 15,
  sym_commit_line = 16,
  sym_sha = 17,
  sym_info_line = 18,
  sym_blank_line = 19,
  sym_message = 20,
  sym_subject = 21,
  sym_overflow = 22,
  sym_message_line = 23,
  sym_text = 24,
  aux_sym_document_repeat1 = 25,
  aux_sym_document_repeat2 = 26,
  aux_sym_commit_repeat1 = 27,
  aux_sym_message_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_commit] = "commit",
  [aux_sym_commit_line_token1] = "commit_line_token1",
  [anon_sym_LF] = "\n",
  [aux_sym_sha_token1] = "short_sha",
  [aux_sym_sha_token2] = "sha_token2",
  [sym_comment] = "comment",
  [sym_info_key] = "info_key",
  [sym_info_value] = "info_value",
  [aux_sym_blank_line_token1] = "blank_line_token1",
  [sym_subject_text] = "subject_text",
  [aux_sym_overflow_token1] = "overflow_token1",
  [sym__indent] = "_indent",
  [sym_invalid_line] = "invalid_line",
  [sym_document] = "document",
  [sym_commit] = "commit",
  [sym_commit_line] = "commit_line",
  [sym_sha] = "sha",
  [sym_info_line] = "info_line",
  [sym_blank_line] = "blank_line",
  [sym_message] = "message",
  [sym_subject] = "subject",
  [sym_overflow] = "overflow",
  [sym_message_line] = "message_line",
  [sym_text] = "text",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_document_repeat2] = "document_repeat2",
  [aux_sym_commit_repeat1] = "commit_repeat1",
  [aux_sym_message_repeat1] = "message_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_commit] = anon_sym_commit,
  [aux_sym_commit_line_token1] = aux_sym_commit_line_token1,
  [anon_sym_LF] = anon_sym_LF,
  [aux_sym_sha_token1] = aux_sym_sha_token1,
  [aux_sym_sha_token2] = aux_sym_sha_token2,
  [sym_comment] = sym_comment,
  [sym_info_key] = sym_info_key,
  [sym_info_value] = sym_info_value,
  [aux_sym_blank_line_token1] = aux_sym_blank_line_token1,
  [sym_subject_text] = sym_subject_text,
  [aux_sym_overflow_token1] = aux_sym_overflow_token1,
  [sym__indent] = sym__indent,
  [sym_invalid_line] = sym_invalid_line,
  [sym_document] = sym_document,
  [sym_commit] = sym_commit,
  [sym_commit_line] = sym_commit_line,
  [sym_sha] = sym_sha,
  [sym_info_line] = sym_info_line,
  [sym_blank_line] = sym_blank_line,
  [sym_message] = sym_message,
  [sym_subject] = sym_subject,
  [sym_overflow] = sym_overflow,
  [sym_message_line] = sym_message_line,
  [sym_text] = sym_text,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_document_repeat2] = aux_sym_document_repeat2,
  [aux_sym_commit_repeat1] = aux_sym_commit_repeat1,
  [aux_sym_message_repeat1] = aux_sym_message_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_commit] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_commit_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_sha_token1] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_sha_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_info_key] = {
    .visible = true,
    .named = true,
  },
  [sym_info_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_blank_line_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_subject_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_overflow_token1] = {
    .visible = false,
    .named = false,
  },
  [sym__indent] = {
    .visible = false,
    .named = true,
  },
  [sym_invalid_line] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_commit] = {
    .visible = true,
    .named = true,
  },
  [sym_commit_line] = {
    .visible = true,
    .named = true,
  },
  [sym_sha] = {
    .visible = true,
    .named = true,
  },
  [sym_info_line] = {
    .visible = true,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_message] = {
    .visible = true,
    .named = true,
  },
  [sym_subject] = {
    .visible = true,
    .named = true,
  },
  [sym_overflow] = {
    .visible = true,
    .named = true,
  },
  [sym_message_line] = {
    .visible = true,
    .named = true,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_document_repeat2] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_commit_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_message_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_key = 1,
  field_overflow = 2,
  field_sha = 3,
  field_value = 4,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_key] = "key",
  [field_overflow] = "overflow",
  [field_sha] = "sha",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 2},
  [3] = {.index = 3, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_sha, 2},
  [1] =
    {field_key, 0},
    {field_value, 1},
  [3] =
    {field_overflow, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(95);
      if (lookahead == '\t') ADVANCE(256);
      if (lookahead == '\n') ADVANCE(102);
      if (lookahead == ' ') ADVANCE(100);
      if (lookahead == '#') ADVANCE(6);
      if (lookahead == 'c') ADVANCE(16);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(25);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(27);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == ' ') ADVANCE(256);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 2:
      if (lookahead == '\t') ADVANCE(27);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == ' ') ADVANCE(1);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 3:
      if (lookahead == '\t') ADVANCE(27);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == ' ') ADVANCE(2);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(102);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(101);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(49);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(102);
      if (lookahead != 0) ADVANCE(255);
      END_STATE();
    case 6:
      if (lookahead == '\n') ADVANCE(106);
      if (lookahead != 0) ADVANCE(6);
      END_STATE();
    case 7:
      if (lookahead == '\n') ADVANCE(257);
      if (lookahead == ':') ADVANCE(107);
      if (lookahead == 'i') ADVANCE(11);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 8:
      if (lookahead == '\n') ADVANCE(257);
      if (lookahead == ':') ADVANCE(107);
      if (lookahead == 'm') ADVANCE(7);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 9:
      if (lookahead == '\n') ADVANCE(257);
      if (lookahead == ':') ADVANCE(107);
      if (lookahead == 'm') ADVANCE(8);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 10:
      if (lookahead == '\n') ADVANCE(257);
      if (lookahead == ':') ADVANCE(107);
      if (lookahead == 'o') ADVANCE(9);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 11:
      if (lookahead == '\n') ADVANCE(257);
      if (lookahead == ':') ADVANCE(107);
      if (lookahead == 't') ADVANCE(97);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 12:
      if (lookahead == '\n') ADVANCE(257);
      if (lookahead == ':') ADVANCE(107);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 13:
      if (lookahead == '\n') ADVANCE(257);
      if (lookahead == 'i') ADVANCE(18);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 14:
      if (lookahead == '\n') ADVANCE(257);
      if (lookahead == 'm') ADVANCE(13);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 15:
      if (lookahead == '\n') ADVANCE(257);
      if (lookahead == 'm') ADVANCE(14);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 16:
      if (lookahead == '\n') ADVANCE(257);
      if (lookahead == 'o') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(24);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 17:
      if (lookahead == '\n') ADVANCE(257);
      if (lookahead == 'o') ADVANCE(15);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 18:
      if (lookahead == '\n') ADVANCE(257);
      if (lookahead == 't') ADVANCE(96);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 19:
      if (lookahead == '\n') ADVANCE(257);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(103);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 20:
      if (lookahead == '\n') ADVANCE(257);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(19);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 21:
      if (lookahead == '\n') ADVANCE(257);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(20);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 22:
      if (lookahead == '\n') ADVANCE(257);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(21);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 23:
      if (lookahead == '\n') ADVANCE(257);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(22);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 24:
      if (lookahead == '\n') ADVANCE(257);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(23);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 25:
      if (lookahead == '\n') ADVANCE(257);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(24);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 26:
      if (lookahead == '\n') ADVANCE(257);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 27:
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(27);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 28:
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(254);
      if (lookahead != 0) ADVANCE(255);
      END_STATE();
    case 29:
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(182);
      if (lookahead != 0) ADVANCE(253);
      END_STATE();
    case 30:
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(30);
      END_STATE();
    case 31:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(103);
      END_STATE();
    case 32:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(105);
      END_STATE();
    case 33:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(104);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(31);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(32);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(33);
      END_STATE();
    case 37:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(34);
      END_STATE();
    case 38:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(35);
      END_STATE();
    case 39:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(36);
      END_STATE();
    case 40:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(37);
      END_STATE();
    case 41:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(38);
      END_STATE();
    case 42:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(39);
      END_STATE();
    case 43:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(40);
      END_STATE();
    case 44:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(41);
      END_STATE();
    case 45:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(42);
      END_STATE();
    case 46:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(43);
      END_STATE();
    case 47:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(44);
      END_STATE();
    case 48:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(45);
      END_STATE();
    case 49:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(46);
      END_STATE();
    case 50:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(47);
      END_STATE();
    case 51:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(48);
      END_STATE();
    case 52:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(50);
      END_STATE();
    case 53:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(51);
      END_STATE();
    case 54:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(52);
      END_STATE();
    case 55:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(53);
      END_STATE();
    case 56:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(54);
      END_STATE();
    case 57:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(55);
      END_STATE();
    case 58:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(56);
      END_STATE();
    case 59:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(57);
      END_STATE();
    case 60:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(58);
      END_STATE();
    case 61:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(59);
      END_STATE();
    case 62:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(60);
      END_STATE();
    case 63:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(61);
      END_STATE();
    case 64:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(62);
      END_STATE();
    case 65:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(63);
      END_STATE();
    case 66:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(64);
      END_STATE();
    case 67:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(65);
      END_STATE();
    case 68:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(66);
      END_STATE();
    case 69:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(67);
      END_STATE();
    case 70:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(68);
      END_STATE();
    case 71:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(69);
      END_STATE();
    case 72:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(70);
      END_STATE();
    case 73:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(71);
      END_STATE();
    case 74:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(72);
      END_STATE();
    case 75:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(73);
      END_STATE();
    case 76:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(74);
      END_STATE();
    case 77:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(75);
      END_STATE();
    case 78:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(76);
      END_STATE();
    case 79:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(77);
      END_STATE();
    case 80:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(78);
      END_STATE();
    case 81:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(79);
      END_STATE();
    case 82:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(80);
      END_STATE();
    case 83:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(81);
      END_STATE();
    case 84:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(82);
      END_STATE();
    case 85:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(84);
      END_STATE();
    case 86:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(85);
      END_STATE();
    case 87:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(86);
      END_STATE();
    case 88:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(87);
      END_STATE();
    case 89:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(88);
      END_STATE();
    case 90:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(89);
      END_STATE();
    case 91:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(90);
      END_STATE();
    case 92:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(91);
      END_STATE();
    case 93:
      if (eof) ADVANCE(95);
      if (lookahead == '\t') ADVANCE(256);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == ' ') ADVANCE(3);
      if (lookahead == '#') ADVANCE(6);
      if (lookahead == 'c') ADVANCE(17);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 94:
      if (eof) ADVANCE(95);
      if (lookahead == '\t') ADVANCE(256);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == ' ') ADVANCE(3);
      if (lookahead == '#') ADVANCE(6);
      if (lookahead == 'c') ADVANCE(10);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      if (lookahead != 0) ADVANCE(26);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(anon_sym_commit);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_commit);
      if (lookahead == ':') ADVANCE(107);
      if (lookahead == '-' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(12);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym_commit_line_token1);
      if (lookahead == '\t') ADVANCE(101);
      if (lookahead == ' ') ADVANCE(256);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(aux_sym_commit_line_token1);
      if (lookahead == '\t') ADVANCE(101);
      if (lookahead == ' ') ADVANCE(98);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(aux_sym_commit_line_token1);
      if (lookahead == '\t') ADVANCE(101);
      if (lookahead == ' ') ADVANCE(99);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(aux_sym_commit_line_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(101);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_LF);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(aux_sym_sha_token1);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(aux_sym_sha_token2);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_sha_token2);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(83);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(sym_info_key);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(sym_info_value);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(108);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(aux_sym_blank_line_token1);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(sym_subject_text);
      END_STATE();
    case 111:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(112);
      if (lookahead != 0) ADVANCE(110);
      END_STATE();
    case 112:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(30);
      END_STATE();
    case 113:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(111);
      if (lookahead != 0) ADVANCE(183);
      END_STATE();
    case 114:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(113);
      if (lookahead != 0) ADVANCE(184);
      END_STATE();
    case 115:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(114);
      if (lookahead != 0) ADVANCE(185);
      END_STATE();
    case 116:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(115);
      if (lookahead != 0) ADVANCE(186);
      END_STATE();
    case 117:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(116);
      if (lookahead != 0) ADVANCE(187);
      END_STATE();
    case 118:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(117);
      if (lookahead != 0) ADVANCE(188);
      END_STATE();
    case 119:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(118);
      if (lookahead != 0) ADVANCE(189);
      END_STATE();
    case 120:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(119);
      if (lookahead != 0) ADVANCE(190);
      END_STATE();
    case 121:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(120);
      if (lookahead != 0) ADVANCE(191);
      END_STATE();
    case 122:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(121);
      if (lookahead != 0) ADVANCE(192);
      END_STATE();
    case 123:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(122);
      if (lookahead != 0) ADVANCE(193);
      END_STATE();
    case 124:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(123);
      if (lookahead != 0) ADVANCE(194);
      END_STATE();
    case 125:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(124);
      if (lookahead != 0) ADVANCE(195);
      END_STATE();
    case 126:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(125);
      if (lookahead != 0) ADVANCE(196);
      END_STATE();
    case 127:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(126);
      if (lookahead != 0) ADVANCE(197);
      END_STATE();
    case 128:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(127);
      if (lookahead != 0) ADVANCE(198);
      END_STATE();
    case 129:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(128);
      if (lookahead != 0) ADVANCE(199);
      END_STATE();
    case 130:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(129);
      if (lookahead != 0) ADVANCE(200);
      END_STATE();
    case 131:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(130);
      if (lookahead != 0) ADVANCE(201);
      END_STATE();
    case 132:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(131);
      if (lookahead != 0) ADVANCE(202);
      END_STATE();
    case 133:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(132);
      if (lookahead != 0) ADVANCE(203);
      END_STATE();
    case 134:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(133);
      if (lookahead != 0) ADVANCE(204);
      END_STATE();
    case 135:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(134);
      if (lookahead != 0) ADVANCE(205);
      END_STATE();
    case 136:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(135);
      if (lookahead != 0) ADVANCE(206);
      END_STATE();
    case 137:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(136);
      if (lookahead != 0) ADVANCE(207);
      END_STATE();
    case 138:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(137);
      if (lookahead != 0) ADVANCE(208);
      END_STATE();
    case 139:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(138);
      if (lookahead != 0) ADVANCE(209);
      END_STATE();
    case 140:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(139);
      if (lookahead != 0) ADVANCE(210);
      END_STATE();
    case 141:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(140);
      if (lookahead != 0) ADVANCE(211);
      END_STATE();
    case 142:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(141);
      if (lookahead != 0) ADVANCE(212);
      END_STATE();
    case 143:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(142);
      if (lookahead != 0) ADVANCE(213);
      END_STATE();
    case 144:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(143);
      if (lookahead != 0) ADVANCE(214);
      END_STATE();
    case 145:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(144);
      if (lookahead != 0) ADVANCE(215);
      END_STATE();
    case 146:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(145);
      if (lookahead != 0) ADVANCE(216);
      END_STATE();
    case 147:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(146);
      if (lookahead != 0) ADVANCE(217);
      END_STATE();
    case 148:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(147);
      if (lookahead != 0) ADVANCE(218);
      END_STATE();
    case 149:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(148);
      if (lookahead != 0) ADVANCE(219);
      END_STATE();
    case 150:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(149);
      if (lookahead != 0) ADVANCE(220);
      END_STATE();
    case 151:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(150);
      if (lookahead != 0) ADVANCE(221);
      END_STATE();
    case 152:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(151);
      if (lookahead != 0) ADVANCE(222);
      END_STATE();
    case 153:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(152);
      if (lookahead != 0) ADVANCE(223);
      END_STATE();
    case 154:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(153);
      if (lookahead != 0) ADVANCE(224);
      END_STATE();
    case 155:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(154);
      if (lookahead != 0) ADVANCE(225);
      END_STATE();
    case 156:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(155);
      if (lookahead != 0) ADVANCE(226);
      END_STATE();
    case 157:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(156);
      if (lookahead != 0) ADVANCE(227);
      END_STATE();
    case 158:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(157);
      if (lookahead != 0) ADVANCE(228);
      END_STATE();
    case 159:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(158);
      if (lookahead != 0) ADVANCE(229);
      END_STATE();
    case 160:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(159);
      if (lookahead != 0) ADVANCE(230);
      END_STATE();
    case 161:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(160);
      if (lookahead != 0) ADVANCE(231);
      END_STATE();
    case 162:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(161);
      if (lookahead != 0) ADVANCE(232);
      END_STATE();
    case 163:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(162);
      if (lookahead != 0) ADVANCE(233);
      END_STATE();
    case 164:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(163);
      if (lookahead != 0) ADVANCE(234);
      END_STATE();
    case 165:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(164);
      if (lookahead != 0) ADVANCE(235);
      END_STATE();
    case 166:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(165);
      if (lookahead != 0) ADVANCE(236);
      END_STATE();
    case 167:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(166);
      if (lookahead != 0) ADVANCE(237);
      END_STATE();
    case 168:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(167);
      if (lookahead != 0) ADVANCE(238);
      END_STATE();
    case 169:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(168);
      if (lookahead != 0) ADVANCE(239);
      END_STATE();
    case 170:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(169);
      if (lookahead != 0) ADVANCE(240);
      END_STATE();
    case 171:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(170);
      if (lookahead != 0) ADVANCE(241);
      END_STATE();
    case 172:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(171);
      if (lookahead != 0) ADVANCE(242);
      END_STATE();
    case 173:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(172);
      if (lookahead != 0) ADVANCE(243);
      END_STATE();
    case 174:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(173);
      if (lookahead != 0) ADVANCE(244);
      END_STATE();
    case 175:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(174);
      if (lookahead != 0) ADVANCE(245);
      END_STATE();
    case 176:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(175);
      if (lookahead != 0) ADVANCE(246);
      END_STATE();
    case 177:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(176);
      if (lookahead != 0) ADVANCE(247);
      END_STATE();
    case 178:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(177);
      if (lookahead != 0) ADVANCE(248);
      END_STATE();
    case 179:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(178);
      if (lookahead != 0) ADVANCE(249);
      END_STATE();
    case 180:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(179);
      if (lookahead != 0) ADVANCE(250);
      END_STATE();
    case 181:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(180);
      if (lookahead != 0) ADVANCE(251);
      END_STATE();
    case 182:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(181);
      if (lookahead != 0) ADVANCE(252);
      END_STATE();
    case 183:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(110);
      END_STATE();
    case 184:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(183);
      END_STATE();
    case 185:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(184);
      END_STATE();
    case 186:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(185);
      END_STATE();
    case 187:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(186);
      END_STATE();
    case 188:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(187);
      END_STATE();
    case 189:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(188);
      END_STATE();
    case 190:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(189);
      END_STATE();
    case 191:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(190);
      END_STATE();
    case 192:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(191);
      END_STATE();
    case 193:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(192);
      END_STATE();
    case 194:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(193);
      END_STATE();
    case 195:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(194);
      END_STATE();
    case 196:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(195);
      END_STATE();
    case 197:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(196);
      END_STATE();
    case 198:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(197);
      END_STATE();
    case 199:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(198);
      END_STATE();
    case 200:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(199);
      END_STATE();
    case 201:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(200);
      END_STATE();
    case 202:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(201);
      END_STATE();
    case 203:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(202);
      END_STATE();
    case 204:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(203);
      END_STATE();
    case 205:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(204);
      END_STATE();
    case 206:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(205);
      END_STATE();
    case 207:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(206);
      END_STATE();
    case 208:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(207);
      END_STATE();
    case 209:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(208);
      END_STATE();
    case 210:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(209);
      END_STATE();
    case 211:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(210);
      END_STATE();
    case 212:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(211);
      END_STATE();
    case 213:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(212);
      END_STATE();
    case 214:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(213);
      END_STATE();
    case 215:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(214);
      END_STATE();
    case 216:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(215);
      END_STATE();
    case 217:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(216);
      END_STATE();
    case 218:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(217);
      END_STATE();
    case 219:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(218);
      END_STATE();
    case 220:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(219);
      END_STATE();
    case 221:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(220);
      END_STATE();
    case 222:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(221);
      END_STATE();
    case 223:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(222);
      END_STATE();
    case 224:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(223);
      END_STATE();
    case 225:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(224);
      END_STATE();
    case 226:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(225);
      END_STATE();
    case 227:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(226);
      END_STATE();
    case 228:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(227);
      END_STATE();
    case 229:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(228);
      END_STATE();
    case 230:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(229);
      END_STATE();
    case 231:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(230);
      END_STATE();
    case 232:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(231);
      END_STATE();
    case 233:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(232);
      END_STATE();
    case 234:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(233);
      END_STATE();
    case 235:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(234);
      END_STATE();
    case 236:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(235);
      END_STATE();
    case 237:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(236);
      END_STATE();
    case 238:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(237);
      END_STATE();
    case 239:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(238);
      END_STATE();
    case 240:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(239);
      END_STATE();
    case 241:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(240);
      END_STATE();
    case 242:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(241);
      END_STATE();
    case 243:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(242);
      END_STATE();
    case 244:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(243);
      END_STATE();
    case 245:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(244);
      END_STATE();
    case 246:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(245);
      END_STATE();
    case 247:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(246);
      END_STATE();
    case 248:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(247);
      END_STATE();
    case 249:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(248);
      END_STATE();
    case 250:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(249);
      END_STATE();
    case 251:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(250);
      END_STATE();
    case 252:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(251);
      END_STATE();
    case 253:
      ACCEPT_TOKEN(sym_subject_text);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(252);
      END_STATE();
    case 254:
      ACCEPT_TOKEN(aux_sym_overflow_token1);
      if (lookahead == '\n') ADVANCE(109);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(254);
      if (lookahead != 0) ADVANCE(255);
      END_STATE();
    case 255:
      ACCEPT_TOKEN(aux_sym_overflow_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(255);
      END_STATE();
    case 256:
      ACCEPT_TOKEN(sym__indent);
      END_STATE();
    case 257:
      ACCEPT_TOKEN(sym_invalid_line);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 93},
  [2] = {.lex_state = 94},
  [3] = {.lex_state = 94},
  [4] = {.lex_state = 93},
  [5] = {.lex_state = 94},
  [6] = {.lex_state = 93},
  [7] = {.lex_state = 93},
  [8] = {.lex_state = 93},
  [9] = {.lex_state = 93},
  [10] = {.lex_state = 94},
  [11] = {.lex_state = 94},
  [12] = {.lex_state = 94},
  [13] = {.lex_state = 94},
  [14] = {.lex_state = 94},
  [15] = {.lex_state = 93},
  [16] = {.lex_state = 93},
  [17] = {.lex_state = 93},
  [18] = {.lex_state = 0},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 28},
  [22] = {.lex_state = 5},
  [23] = {.lex_state = 4},
  [24] = {.lex_state = 29},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 4},
  [27] = {.lex_state = 4},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 4},
  [31] = {.lex_state = 108},
  [32] = {.lex_state = 92},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 28},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_commit] = ACTIONS(1),
    [aux_sym_commit_line_token1] = ACTIONS(1),
    [anon_sym_LF] = ACTIONS(1),
    [aux_sym_sha_token1] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym__indent] = ACTIONS(1),
    [sym_invalid_line] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(37),
    [sym_commit] = STATE(18),
    [sym_commit_line] = STATE(3),
    [sym_blank_line] = STATE(4),
    [aux_sym_document_repeat1] = STATE(4),
    [aux_sym_document_repeat2] = STATE(18),
    [ts_builtin_sym_end] = ACTIONS(3),
    [anon_sym_commit] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [aux_sym_blank_line_token1] = ACTIONS(9),
    [sym__indent] = ACTIONS(11),
    [sym_invalid_line] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 10,
    ACTIONS(9), 1,
      aux_sym_blank_line_token1,
    ACTIONS(15), 1,
      ts_builtin_sym_end,
    ACTIONS(17), 1,
      anon_sym_commit,
    ACTIONS(19), 1,
      sym_comment,
    ACTIONS(21), 1,
      sym_info_key,
    ACTIONS(23), 1,
      sym__indent,
    ACTIONS(25), 1,
      sym_invalid_line,
    STATE(6), 1,
      sym_subject,
    STATE(25), 1,
      sym_message,
    STATE(5), 3,
      sym_info_line,
      sym_blank_line,
      aux_sym_commit_repeat1,
  [33] = 10,
    ACTIONS(9), 1,
      aux_sym_blank_line_token1,
    ACTIONS(21), 1,
      sym_info_key,
    ACTIONS(23), 1,
      sym__indent,
    ACTIONS(27), 1,
      ts_builtin_sym_end,
    ACTIONS(29), 1,
      anon_sym_commit,
    ACTIONS(31), 1,
      sym_comment,
    ACTIONS(33), 1,
      sym_invalid_line,
    STATE(6), 1,
      sym_subject,
    STATE(28), 1,
      sym_message,
    STATE(2), 3,
      sym_info_line,
      sym_blank_line,
      aux_sym_commit_repeat1,
  [66] = 9,
    ACTIONS(5), 1,
      anon_sym_commit,
    ACTIONS(9), 1,
      aux_sym_blank_line_token1,
    ACTIONS(11), 1,
      sym__indent,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    ACTIONS(37), 1,
      sym_comment,
    ACTIONS(39), 1,
      sym_invalid_line,
    STATE(3), 1,
      sym_commit_line,
    STATE(9), 2,
      sym_blank_line,
      aux_sym_document_repeat1,
    STATE(19), 2,
      sym_commit,
      aux_sym_document_repeat2,
  [96] = 8,
    ACTIONS(41), 1,
      ts_builtin_sym_end,
    ACTIONS(43), 1,
      anon_sym_commit,
    ACTIONS(45), 1,
      sym_comment,
    ACTIONS(48), 1,
      sym_info_key,
    ACTIONS(51), 1,
      aux_sym_blank_line_token1,
    ACTIONS(54), 1,
      sym__indent,
    ACTIONS(57), 1,
      sym_invalid_line,
    STATE(5), 3,
      sym_info_line,
      sym_blank_line,
      aux_sym_commit_repeat1,
  [123] = 6,
    ACTIONS(9), 1,
      aux_sym_blank_line_token1,
    ACTIONS(62), 1,
      sym_comment,
    ACTIONS(64), 1,
      sym__indent,
    ACTIONS(66), 1,
      sym_invalid_line,
    ACTIONS(60), 2,
      ts_builtin_sym_end,
      anon_sym_commit,
    STATE(7), 3,
      sym_blank_line,
      sym_message_line,
      aux_sym_message_repeat1,
  [145] = 6,
    ACTIONS(9), 1,
      aux_sym_blank_line_token1,
    ACTIONS(64), 1,
      sym__indent,
    ACTIONS(70), 1,
      sym_comment,
    ACTIONS(72), 1,
      sym_invalid_line,
    ACTIONS(68), 2,
      ts_builtin_sym_end,
      anon_sym_commit,
    STATE(8), 3,
      sym_blank_line,
      sym_message_line,
      aux_sym_message_repeat1,
  [167] = 6,
    ACTIONS(76), 1,
      sym_comment,
    ACTIONS(79), 1,
      aux_sym_blank_line_token1,
    ACTIONS(82), 1,
      sym__indent,
    ACTIONS(85), 1,
      sym_invalid_line,
    ACTIONS(74), 2,
      ts_builtin_sym_end,
      anon_sym_commit,
    STATE(8), 3,
      sym_blank_line,
      sym_message_line,
      aux_sym_message_repeat1,
  [189] = 6,
    ACTIONS(90), 1,
      sym_comment,
    ACTIONS(93), 1,
      aux_sym_blank_line_token1,
    ACTIONS(96), 1,
      sym__indent,
    ACTIONS(99), 1,
      sym_invalid_line,
    ACTIONS(88), 2,
      ts_builtin_sym_end,
      anon_sym_commit,
    STATE(9), 2,
      sym_blank_line,
      aux_sym_document_repeat1,
  [210] = 2,
    ACTIONS(104), 3,
      anon_sym_commit,
      aux_sym_blank_line_token1,
      sym_invalid_line,
    ACTIONS(102), 4,
      ts_builtin_sym_end,
      sym_comment,
      sym_info_key,
      sym__indent,
  [222] = 2,
    ACTIONS(108), 3,
      anon_sym_commit,
      aux_sym_blank_line_token1,
      sym_invalid_line,
    ACTIONS(106), 4,
      ts_builtin_sym_end,
      sym_comment,
      sym_info_key,
      sym__indent,
  [234] = 2,
    ACTIONS(112), 3,
      anon_sym_commit,
      aux_sym_blank_line_token1,
      sym_invalid_line,
    ACTIONS(110), 4,
      ts_builtin_sym_end,
      sym_comment,
      sym_info_key,
      sym__indent,
  [246] = 2,
    ACTIONS(116), 3,
      anon_sym_commit,
      aux_sym_blank_line_token1,
      sym_invalid_line,
    ACTIONS(114), 4,
      ts_builtin_sym_end,
      sym_comment,
      sym_info_key,
      sym__indent,
  [258] = 2,
    ACTIONS(120), 3,
      anon_sym_commit,
      aux_sym_blank_line_token1,
      sym_invalid_line,
    ACTIONS(118), 4,
      ts_builtin_sym_end,
      sym_comment,
      sym_info_key,
      sym__indent,
  [270] = 2,
    ACTIONS(124), 2,
      aux_sym_blank_line_token1,
      sym_invalid_line,
    ACTIONS(122), 4,
      ts_builtin_sym_end,
      anon_sym_commit,
      sym_comment,
      sym__indent,
  [281] = 2,
    ACTIONS(128), 2,
      aux_sym_blank_line_token1,
      sym_invalid_line,
    ACTIONS(126), 4,
      ts_builtin_sym_end,
      anon_sym_commit,
      sym_comment,
      sym__indent,
  [292] = 2,
    ACTIONS(132), 2,
      aux_sym_blank_line_token1,
      sym_invalid_line,
    ACTIONS(130), 4,
      ts_builtin_sym_end,
      anon_sym_commit,
      sym_comment,
      sym__indent,
  [303] = 4,
    ACTIONS(5), 1,
      anon_sym_commit,
    ACTIONS(35), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      sym_commit_line,
    STATE(20), 2,
      sym_commit,
      aux_sym_document_repeat2,
  [317] = 4,
    ACTIONS(5), 1,
      anon_sym_commit,
    ACTIONS(134), 1,
      ts_builtin_sym_end,
    STATE(3), 1,
      sym_commit_line,
    STATE(20), 2,
      sym_commit,
      aux_sym_document_repeat2,
  [331] = 4,
    ACTIONS(136), 1,
      ts_builtin_sym_end,
    ACTIONS(138), 1,
      anon_sym_commit,
    STATE(3), 1,
      sym_commit_line,
    STATE(20), 2,
      sym_commit,
      aux_sym_document_repeat2,
  [345] = 3,
    ACTIONS(141), 1,
      aux_sym_blank_line_token1,
    ACTIONS(143), 1,
      aux_sym_overflow_token1,
    STATE(36), 1,
      sym_text,
  [355] = 3,
    ACTIONS(145), 1,
      anon_sym_LF,
    ACTIONS(147), 1,
      aux_sym_overflow_token1,
    STATE(34), 1,
      sym_overflow,
  [365] = 2,
    ACTIONS(149), 1,
      aux_sym_commit_line_token1,
    ACTIONS(151), 1,
      anon_sym_LF,
  [372] = 2,
    ACTIONS(141), 1,
      aux_sym_blank_line_token1,
    ACTIONS(153), 1,
      sym_subject_text,
  [379] = 1,
    ACTIONS(155), 2,
      ts_builtin_sym_end,
      anon_sym_commit,
  [384] = 2,
    ACTIONS(157), 1,
      aux_sym_sha_token1,
    STATE(23), 1,
      sym_sha,
  [391] = 1,
    ACTIONS(159), 2,
      aux_sym_commit_line_token1,
      anon_sym_LF,
  [396] = 1,
    ACTIONS(15), 2,
      ts_builtin_sym_end,
      anon_sym_commit,
  [401] = 1,
    ACTIONS(161), 1,
      anon_sym_LF,
  [405] = 1,
    ACTIONS(163), 1,
      aux_sym_commit_line_token1,
  [409] = 1,
    ACTIONS(165), 1,
      sym_info_value,
  [413] = 1,
    ACTIONS(167), 1,
      aux_sym_sha_token2,
  [417] = 1,
    ACTIONS(169), 1,
      anon_sym_LF,
  [421] = 1,
    ACTIONS(171), 1,
      anon_sym_LF,
  [425] = 1,
    ACTIONS(173), 1,
      anon_sym_LF,
  [429] = 1,
    ACTIONS(175), 1,
      anon_sym_LF,
  [433] = 1,
    ACTIONS(177), 1,
      ts_builtin_sym_end,
  [437] = 1,
    ACTIONS(179), 1,
      anon_sym_LF,
  [441] = 1,
    ACTIONS(141), 1,
      aux_sym_blank_line_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 33,
  [SMALL_STATE(4)] = 66,
  [SMALL_STATE(5)] = 96,
  [SMALL_STATE(6)] = 123,
  [SMALL_STATE(7)] = 145,
  [SMALL_STATE(8)] = 167,
  [SMALL_STATE(9)] = 189,
  [SMALL_STATE(10)] = 210,
  [SMALL_STATE(11)] = 222,
  [SMALL_STATE(12)] = 234,
  [SMALL_STATE(13)] = 246,
  [SMALL_STATE(14)] = 258,
  [SMALL_STATE(15)] = 270,
  [SMALL_STATE(16)] = 281,
  [SMALL_STATE(17)] = 292,
  [SMALL_STATE(18)] = 303,
  [SMALL_STATE(19)] = 317,
  [SMALL_STATE(20)] = 331,
  [SMALL_STATE(21)] = 345,
  [SMALL_STATE(22)] = 355,
  [SMALL_STATE(23)] = 365,
  [SMALL_STATE(24)] = 372,
  [SMALL_STATE(25)] = 379,
  [SMALL_STATE(26)] = 384,
  [SMALL_STATE(27)] = 391,
  [SMALL_STATE(28)] = 396,
  [SMALL_STATE(29)] = 401,
  [SMALL_STATE(30)] = 405,
  [SMALL_STATE(31)] = 409,
  [SMALL_STATE(32)] = 413,
  [SMALL_STATE(33)] = 417,
  [SMALL_STATE(34)] = 421,
  [SMALL_STATE(35)] = 425,
  [SMALL_STATE(36)] = 429,
  [SMALL_STATE(37)] = 433,
  [SMALL_STATE(38)] = 437,
  [SMALL_STATE(39)] = 441,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_commit, 2, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_commit, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_commit, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_commit, 1, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [35] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [39] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_commit_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_commit_repeat1, 2, 0, 0),
  [45] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_commit_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [48] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_commit_repeat1, 2, 0, 0), SHIFT_REPEAT(31),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_commit_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_commit_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_commit_repeat1, 2, 0, 0), SHIFT_REPEAT(5),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(8),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_message_repeat1, 2, 0, 0),
  [76] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_message_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [79] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_message_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_message_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_message_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [93] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [96] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [99] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [102] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blank_line, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_blank_line, 2, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blank_line, 1, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_blank_line, 1, 0, 0),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_commit_line, 4, 0, 1),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_commit_line, 4, 0, 1),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_info_line, 3, 0, 2),
  [116] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_info_line, 3, 0, 2),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_commit_line, 5, 0, 1),
  [120] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_commit_line, 5, 0, 1),
  [122] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 3, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subject, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subject, 4, 0, 3),
  [128] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_subject, 4, 0, 3),
  [130] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_message_line, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_message_line, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 2, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0),
  [138] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat2, 2, 0, 0), SHIFT_REPEAT(30),
  [141] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_commit, 3, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_sha, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [167] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_overflow, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_text, 1, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [177] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [179] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_reword(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "reword",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
